name: Publish Release

on:
  release:
    types:
      - published

jobs:
  publish-artifact:
    runs-on: macos-latest
    if: github.event.release.draft == false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install Required Tools
      run: |
        brew update
        brew install automake
        brew install libtool
        brew install make
        brew reinstall perl
        brew install ant

    - name: Verify Required Tools
      run: |
        automake --version
        pkg-config --version
        make --version
        perl --version

    - name: Build and Archive
      run: |
        ./autogen.sh --without-junit
        ls -alR
      shell: /bin/bash -e {0}
      env:
        MD_APPLE_SDK_ROOT: /Applications/Xcode_16.2.app
        PATH: /usr/local/bin:/usr/local/opt/make/libexec/gnubin:$PATH  # Ensure the new perl and make are used
    
    - name: Upload Artifact to Release
      id: upload-artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: instdir/LibreOfficeDev.app  # Path to the artifact
        asset_name: LibreOfficeDev-macos15-arm64.app  # Name of the artifact in the release
        asset_content_type: application/octet-stream  # Content type for .app files
