name: Publish Release

on:
  release:
    types:
      - published

jobs:
  publish-artifact:
    runs-on: macos-latest
    if: github.event.release.draft == false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Install Required Tools
      run: |
        brew update
        brew install automake
        brew install libtool
        brew install pkg-config

    - name: Build and Archive
      run: |
        ./autogen.sh
        ls -alR
      shell: /bin/bash -e {0}
      env:
        MD_APPLE_SDK_ROOT: /Applications/Xcode_16.2.app